<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bitacora extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bitacora_model');
    } 

    /*
     * Listing of bitacora
     */
    function index()
    {
        $data['bitacora'] = $this->Bitacora_model->get_all_bitacora();
        
        $data['_view'] = 'bitacora/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new bitacora
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'fecha' => $this->input->post('fecha'),
				'hora' => $this->input->post('hora'),
				'ope' => $this->input->post('ope'),
				'usuario' => $this->input->post('usuario'),
				'sentenc' => $this->input->post('sentenc'),
            );
            
            $bitacora_id = $this->Bitacora_model->add_bitacora($params);
            redirect('bitacora/index');
        }
        else
        {            
            $data['_view'] = 'bitacora/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a bitacora
     */
    function edit($id_bit)
    {   
        // check if the bitacora exists before trying to edit it
        $data['bitacora'] = $this->Bitacora_model->get_bitacora($id_bit);
        
        if(isset($data['bitacora']['id_bit']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'fecha' => $this->input->post('fecha'),
					'hora' => $this->input->post('hora'),
					'ope' => $this->input->post('ope'),
					'usuario' => $this->input->post('usuario'),
					'sentenc' => $this->input->post('sentenc'),
                );

                $this->Bitacora_model->update_bitacora($id_bit,$params);            
                redirect('bitacora/index');
            }
            else
            {
                $data['_view'] = 'bitacora/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The bitacora you are trying to edit does not exist.');
    } 

    /*
     * Deleting bitacora
     */
    function remove($id_bit)
    {
        $bitacora = $this->Bitacora_model->get_bitacora($id_bit);

        // check if the bitacora exists before trying to delete it
        if(isset($bitacora['id_bit']))
        {
            $this->Bitacora_model->delete_bitacora($id_bit);
            redirect('bitacora/index');
        }
        else
            show_error('The bitacora you are trying to delete does not exist.');
    }
    
}
