<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Documento extends CI_Controller{
    private $session_data = "";
    function __construct()
    {
        parent::__construct();
        $this->load->model('Documento_model');
        if ($this->session->userdata('logged_in')) {
            $this->session_data = $this->session->userdata('logged_in');
        }else {
            redirect('', 'refresh');
        }
    }
    /* *****Funcion que verifica el acceso al sistema**** */
    private function acceso($id_rol){
        $rolusuario = $this->session_data['rol'];
        if($rolusuario[$id_rol-1]['rolusuario_asignado'] == 1){
            return true;
        }else{
            $data['_view'] = 'login/mensajeacceso';
            $this->load->view('layouts/main',$data);
        }
    }
    /*
     * Listing of documento
     */
    function index()
    {
        if($this->acceso(439)){
            $data['all_documento'] = $this->Documento_model->get_all_documento();

            $data['_view'] = 'documento/index';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Adding a new documento
     */
    function add()
    {
        if($this->acceso(439)){
            $this->load->library('form_validation');
            $this->form_validation->set_rules('nombre_doc','Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
            if($this->form_validation->run())     
            {
                $params = array(
                    'nombre_doc' => $this->input->post('nombre_doc'),
                );
                $id_doc = $this->Documento_model->add_documento($params);
                redirect('documento/index');
            }else{            
                $data['_view'] = 'documento/add';
                $this->load->view('layouts/main',$data);
            }
        }
    }  

    /*
     * Editing a documento
     */
    function edit($id_doc)
    {
        if($this->acceso(439)){
            // check if the Diametrored exists before trying to edit it
            $data['documento'] = $this->Documento_model->get_documento($id_doc);

            if(isset($data['documento']['id_doc']))
            {
                $this->load->library('form_validation');
                $this->form_validation->set_rules('nombre_doc','Nombre','trim|required', array('required' => 'Este Campo no debe ser vacio'));
                if($this->form_validation->run())     
                {
                    $params = array(
                        'nombre_doc' => $this->input->post('nombre_doc'),
                    );

                    $this->Documento_model->update_documento($id_doc,$params);            
                    redirect('documento/index');
                }else{
                    $data['_view'] = 'documento/edit';
                    $this->load->view('layouts/main',$data);
                }
            }
            else
                show_error('The documento you are trying to edit does not exist.');
        }
    }
    
    /* * añadir documento */
    /*function aniadirdocumento()
    {
        if ($this->input->is_ajax_request()) {
            $nombre_doc = $this->input->post('nombre_doc');
            if($nombre_doc != ""){
                $params = array(
                'nombre_doc' => $nombre_doc,
                );
                $id_doc = $this->Documento_model->add_documento($params);
                $datos = $this->Documento_model->get_documento($id_doc);
                echo json_encode($datos);
            }else{
                echo json_encode(null);
            }
        }
        else
        {                 
            show_404();
        }
    }*/
}
