<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Empresa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Empresa_model');
    } 

    /*
     * Listing of empresa
     */
    function index()
    {
        $data['empresa'] = $this->Empresa_model->get_all_empresa();
        
        $data['_view'] = 'empresa/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new empresa
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre_emp','Nombre Emp','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nombre_emp' => $this->input->post('nombre_emp'),
				'eslogan_emp' => $this->input->post('eslogan_emp'),
				'direccion_emp' => $this->input->post('direccion_emp'),
				'telefono_emp' => $this->input->post('telefono_emp'),
				'sucursal_emp' => $this->input->post('sucursal_emp'),
				'ubicacion_emp' => $this->input->post('ubicacion_emp'),
				'actividad_emp' => $this->input->post('actividad_emp'),
				'nit_emp' => $this->input->post('nit_emp'),
				'logo_emp' => $this->input->post('logo_emp'),
				'zona_emp' => $this->input->post('zona_emp'),
				'sis_emp' => $this->input->post('sis_emp'),
				'anuncio_emp' => $this->input->post('anuncio_emp'),
            );
            
            $empresa_id = $this->Empresa_model->add_empresa($params);
            redirect('empresa/index');
        }
        else
        {            
            $data['_view'] = 'empresa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a empresa
     */
    function edit($id_emp)
    {   
        // check if the empresa exists before trying to edit it
        $data['empresa'] = $this->Empresa_model->get_empresa($id_emp);
        
        if(isset($data['empresa']['id_emp']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre_emp','Nombre Emp','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nombre_emp' => $this->input->post('nombre_emp'),
					'eslogan_emp' => $this->input->post('eslogan_emp'),
					'direccion_emp' => $this->input->post('direccion_emp'),
					'telefono_emp' => $this->input->post('telefono_emp'),
					'sucursal_emp' => $this->input->post('sucursal_emp'),
					'ubicacion_emp' => $this->input->post('ubicacion_emp'),
					'actividad_emp' => $this->input->post('actividad_emp'),
					'nit_emp' => $this->input->post('nit_emp'),
					'logo_emp' => $this->input->post('logo_emp'),
					'zona_emp' => $this->input->post('zona_emp'),
					'sis_emp' => $this->input->post('sis_emp'),
					'anuncio_emp' => $this->input->post('anuncio_emp'),
                );

                $this->Empresa_model->update_empresa($id_emp,$params);            
                redirect('empresa/index');
            }
            else
            {
                $data['_view'] = 'empresa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The empresa you are trying to edit does not exist.');
    } 

    /*
     * Deleting empresa
     */
    function remove($id_emp)
    {
        $empresa = $this->Empresa_model->get_empresa($id_emp);

        // check if the empresa exists before trying to delete it
        if(isset($empresa['id_emp']))
        {
            $this->Empresa_model->delete_empresa($id_emp);
            redirect('empresa/index');
        }
        else
            show_error('The empresa you are trying to delete does not exist.');
    }
    
}
