<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Expedido extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Expedido_model');
    } 

    /*
     * Listing of expedido
     */
    function index()
    {
        $data['expedido'] = $this->Expedido_model->get_all_expedido();
        
        $data['_view'] = 'expedido/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new expedido
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $expedido_id = $this->Expedido_model->add_expedido($params);
            redirect('expedido/index');
        }
        else
        {            
            $data['_view'] = 'expedido/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a expedido
     */
    function edit($ciudad)
    {   
        // check if the expedido exists before trying to edit it
        $data['expedido'] = $this->Expedido_model->get_expedido($ciudad);
        
        if(isset($data['expedido']['ciudad']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Expedido_model->update_expedido($ciudad,$params);            
                redirect('expedido/index');
            }
            else
            {
                $data['_view'] = 'expedido/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The expedido you are trying to edit does not exist.');
    } 

    /*
     * Deleting expedido
     */
    function remove($ciudad)
    {
        $expedido = $this->Expedido_model->get_expedido($ciudad);

        // check if the expedido exists before trying to delete it
        if(isset($expedido['ciudad']))
        {
            $this->Expedido_model->delete_expedido($ciudad);
            redirect('expedido/index');
        }
        else
            show_error('The expedido you are trying to delete does not exist.');
    }
    
}
