<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gestion extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Gestion_model');
    } 

    /*
     * Listing of gestion
     */
    function index()
    {
        $data['gestion'] = $this->Gestion_model->get_all_gestion();
        
        $data['_view'] = 'gestion/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new gestion
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $gestion_id = $this->Gestion_model->add_gestion($params);
            redirect('gestion/index');
        }
        else
        {            
            $data['_view'] = 'gestion/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a gestion
     */
    function edit($gestion_lec)
    {   
        // check if the gestion exists before trying to edit it
        $data['gestion'] = $this->Gestion_model->get_gestion($gestion_lec);
        
        if(isset($data['gestion']['gestion_lec']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Gestion_model->update_gestion($gestion_lec,$params);            
                redirect('gestion/index');
            }
            else
            {
                $data['_view'] = 'gestion/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The gestion you are trying to edit does not exist.');
    } 

    /*
     * Deleting gestion
     */
    function remove($gestion_lec)
    {
        $gestion = $this->Gestion_model->get_gestion($gestion_lec);

        // check if the gestion exists before trying to delete it
        if(isset($gestion['gestion_lec']))
        {
            $this->Gestion_model->delete_gestion($gestion_lec);
            redirect('gestion/index');
        }
        else
            show_error('The gestion you are trying to delete does not exist.');
    }
    
}
