<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Imagen_asociado extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Imagen_asociado_model');
    } 

    /*
     * Listing of imagen_asociado
     */
    function index()
    {
        $data['imagen_asociado'] = $this->Imagen_asociado_model->get_all_imagen_asociado();
        
        $data['_view'] = 'imagen_asociado/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new imagen_asociado
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'asociado_id' => $this->input->post('asociado_id'),
				'imagenasoc_titulo' => $this->input->post('imagenasoc_titulo'),
				'imagenasoc_archivo' => $this->input->post('imagenasoc_archivo'),
				'imagenasoc_descripcion' => $this->input->post('imagenasoc_descripcion'),
            );
            
            $imagen_asociado_id = $this->Imagen_asociado_model->add_imagen_asociado($params);
            redirect('imagen_asociado/index');
        }
        else
        {
			$this->load->model('Asociado_model');
			$data['all_asociado'] = $this->Asociado_model->get_all_asociado();
            
            $data['_view'] = 'imagen_asociado/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a imagen_asociado
     */
    function edit($imagenasoc_id)
    {   
        // check if the imagen_asociado exists before trying to edit it
        $data['imagen_asociado'] = $this->Imagen_asociado_model->get_imagen_asociado($imagenasoc_id);
        
        if(isset($data['imagen_asociado']['imagenasoc_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'asociado_id' => $this->input->post('asociado_id'),
					'imagenasoc_titulo' => $this->input->post('imagenasoc_titulo'),
					'imagenasoc_archivo' => $this->input->post('imagenasoc_archivo'),
					'imagenasoc_descripcion' => $this->input->post('imagenasoc_descripcion'),
                );

                $this->Imagen_asociado_model->update_imagen_asociado($imagenasoc_id,$params);            
                redirect('imagen_asociado/index');
            }
            else
            {
				$this->load->model('Asociado_model');
				$data['all_asociado'] = $this->Asociado_model->get_all_asociado();

                $data['_view'] = 'imagen_asociado/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The imagen_asociado you are trying to edit does not exist.');
    } 

    /*
     * Deleting imagen_asociado
     */
    function remove($imagenasoc_id)
    {
        $imagen_asociado = $this->Imagen_asociado_model->get_imagen_asociado($imagenasoc_id);

        // check if the imagen_asociado exists before trying to delete it
        if(isset($imagen_asociado['imagenasoc_id']))
        {
            $this->Imagen_asociado_model->delete_imagen_asociado($imagenasoc_id);
            redirect('imagen_asociado/index');
        }
        else
            show_error('The imagen_asociado you are trying to delete does not exist.');
    }
    
}
