<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ingreso_egresox extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ingreso_egresox_model');
    } 

    /*
     * Listing of ingreso_egresox
     */
    function index()
    {
        $data['ingreso_egresox'] = $this->Ingreso_egresox_model->get_all_ingreso_egresox();
        
        $data['_view'] = 'ingreso_egresox/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new ingreso_egresox
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_usu' => $this->input->post('id_usu'),
				'detalle_ing' => $this->input->post('detalle_ing'),
				'nombre_ing' => $this->input->post('nombre_ing'),
				'fechahora_ing' => $this->input->post('fechahora_ing'),
				'monto_ing' => $this->input->post('monto_ing'),
				'descripcion_ing' => $this->input->post('descripcion_ing'),
				'estado_ing' => $this->input->post('estado_ing'),
				'tipo_ing' => $this->input->post('tipo_ing'),
				'numrec_ing' => $this->input->post('numrec_ing'),
				'numrec_egr' => $this->input->post('numrec_egr'),
            );
            
            $ingreso_egresox_id = $this->Ingreso_egresox_model->add_ingreso_egresox($params);
            redirect('ingreso_egresox/index');
        }
        else
        {            
            $data['_view'] = 'ingreso_egresox/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a ingreso_egresox
     */
    function edit($id_ing)
    {   
        // check if the ingreso_egresox exists before trying to edit it
        $data['ingreso_egresox'] = $this->Ingreso_egresox_model->get_ingreso_egresox($id_ing);
        
        if(isset($data['ingreso_egresox']['id_ing']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_usu' => $this->input->post('id_usu'),
					'detalle_ing' => $this->input->post('detalle_ing'),
					'nombre_ing' => $this->input->post('nombre_ing'),
					'fechahora_ing' => $this->input->post('fechahora_ing'),
					'monto_ing' => $this->input->post('monto_ing'),
					'descripcion_ing' => $this->input->post('descripcion_ing'),
					'estado_ing' => $this->input->post('estado_ing'),
					'tipo_ing' => $this->input->post('tipo_ing'),
					'numrec_ing' => $this->input->post('numrec_ing'),
					'numrec_egr' => $this->input->post('numrec_egr'),
                );

                $this->Ingreso_egresox_model->update_ingreso_egresox($id_ing,$params);            
                redirect('ingreso_egresox/index');
            }
            else
            {
                $data['_view'] = 'ingreso_egresox/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The ingreso_egresox you are trying to edit does not exist.');
    } 

    /*
     * Deleting ingreso_egresox
     */
    function remove($id_ing)
    {
        $ingreso_egresox = $this->Ingreso_egresox_model->get_ingreso_egresox($id_ing);

        // check if the ingreso_egresox exists before trying to delete it
        if(isset($ingreso_egresox['id_ing']))
        {
            $this->Ingreso_egresox_model->delete_ingreso_egresox($id_ing);
            redirect('ingreso_egresox/index');
        }
        else
            show_error('The ingreso_egresox you are trying to delete does not exist.');
    }
    
}
