<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mes extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mes_model');
    } 

    /*
     * Listing of mes
     */
    function index()
    {
        $data['mes'] = $this->Mes_model->get_all_mes();
        
        $data['_view'] = 'mes/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new mes
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'mes_lec' => $this->input->post('mes_lec'),
            );
            
            $mes_id = $this->Mes_model->add_mes($params);
            redirect('mes/index');
        }
        else
        {            
            $data['_view'] = 'mes/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a mes
     */
    function edit($id_mes)
    {   
        // check if the mes exists before trying to edit it
        $data['mes'] = $this->Mes_model->get_mes($id_mes);
        
        if(isset($data['mes']['id_mes']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'mes_lec' => $this->input->post('mes_lec'),
                );

                $this->Mes_model->update_mes($id_mes,$params);            
                redirect('mes/index');
            }
            else
            {
                $data['_view'] = 'mes/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The mes you are trying to edit does not exist.');
    } 

    /*
     * Deleting mes
     */
    function remove($id_mes)
    {
        $mes = $this->Mes_model->get_mes($id_mes);

        // check if the mes exists before trying to delete it
        if(isset($mes['id_mes']))
        {
            $this->Mes_model->delete_mes($id_mes);
            redirect('mes/index');
        }
        else
            show_error('The mes you are trying to delete does not exist.');
    }
    
}
