<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rol extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rol_model');
    } 

    /*
     * Listing of rol
     */
    function index()
    {
        $data['rol'] = $this->Rol_model->get_all_rol();
        
        $data['_view'] = 'rol/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new rol
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nom_rol','Nom Rol','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'estado_rol' => $this->input->post('estado_rol'),
				'nom_rol' => $this->input->post('nom_rol'),
				'desc_rol' => $this->input->post('desc_rol'),
            );
            
            $rol_id = $this->Rol_model->add_rol($params);
            redirect('rol/index');
        }
        else
        {            
            $data['_view'] = 'rol/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a rol
     */
    function edit($id_rol)
    {   
        // check if the rol exists before trying to edit it
        $data['rol'] = $this->Rol_model->get_rol($id_rol);
        
        if(isset($data['rol']['id_rol']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nom_rol','Nom Rol','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'estado_rol' => $this->input->post('estado_rol'),
					'nom_rol' => $this->input->post('nom_rol'),
					'desc_rol' => $this->input->post('desc_rol'),
                );

                $this->Rol_model->update_rol($id_rol,$params);            
                redirect('rol/index');
            }
            else
            {
                $data['_view'] = 'rol/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The rol you are trying to edit does not exist.');
    } 

    /*
     * Deleting rol
     */
    function remove($id_rol)
    {
        $rol = $this->Rol_model->get_rol($id_rol);

        // check if the rol exists before trying to delete it
        if(isset($rol['id_rol']))
        {
            $this->Rol_model->delete_rol($id_rol);
            redirect('rol/index');
        }
        else
            show_error('The rol you are trying to delete does not exist.');
    }
    
}
