<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Servicio extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Servicio_model');
    } 

    /*
     * Listing of servicios
     */
    function index()
    {
        $data['servicios'] = $this->Servicio_model->get_all_servicios();
        
        $data['_view'] = 'servicio/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new servicio
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $servicio_id = $this->Servicio_model->add_servicio($params);
            redirect('servicio/index');
        }
        else
        {            
            $data['_view'] = 'servicio/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a servicio
     */
    function edit($servicio)
    {   
        // check if the servicio exists before trying to edit it
        $data['servicio'] = $this->Servicio_model->get_servicio($servicio);
        
        if(isset($data['servicio']['servicio']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Servicio_model->update_servicio($servicio,$params);            
                redirect('servicio/index');
            }
            else
            {
                $data['_view'] = 'servicio/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The servicio you are trying to edit does not exist.');
    } 

    /*
     * Deleting servicio
     */
    function remove($servicio)
    {
        $servicio = $this->Servicio_model->get_servicio($servicio);

        // check if the servicio exists before trying to delete it
        if(isset($servicio['servicio']))
        {
            $this->Servicio_model->delete_servicio($servicio);
            redirect('servicio/index');
        }
        else
            show_error('The servicio you are trying to delete does not exist.');
    }
    
}
