<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tarifa_parametrizable extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tarifa_parametrizable_model');
    } 

    /*
     * Listing of tarifa_parametrizable
     */
    function index()
    {
        $data['tarifa_parametrizable'] = $this->Tarifa_parametrizable_model->get_all_tarifa_parametrizable();
        
        $data['_view'] = 'tarifa_parametrizable/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tarifa_parametrizable
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tipo' => $this->input->post('tipo'),
				'desde' => $this->input->post('desde'),
				'hasta' => $this->input->post('hasta'),
				'costo_m3' => $this->input->post('costo_m3'),
				'costo_fijo' => $this->input->post('costo_fijo'),
				'porc_alcant' => $this->input->post('porc_alcant'),
				'porc_factura' => $this->input->post('porc_factura'),
				'montofijo_extra' => $this->input->post('montofijo_extra'),
            );
            
            $tarifa_parametrizable_id = $this->Tarifa_parametrizable_model->add_tarifa_parametrizable($params);
            redirect('tarifa_parametrizable/index');
        }
        else
        {            
            $data['_view'] = 'tarifa_parametrizable/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tarifa_parametrizable
     */
    function edit($id_tarifa)
    {   
        // check if the tarifa_parametrizable exists before trying to edit it
        $data['tarifa_parametrizable'] = $this->Tarifa_parametrizable_model->get_tarifa_parametrizable($id_tarifa);
        
        if(isset($data['tarifa_parametrizable']['id_tarifa']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tipo' => $this->input->post('tipo'),
					'desde' => $this->input->post('desde'),
					'hasta' => $this->input->post('hasta'),
					'costo_m3' => $this->input->post('costo_m3'),
					'costo_fijo' => $this->input->post('costo_fijo'),
					'porc_alcant' => $this->input->post('porc_alcant'),
					'porc_factura' => $this->input->post('porc_factura'),
					'montofijo_extra' => $this->input->post('montofijo_extra'),
                );

                $this->Tarifa_parametrizable_model->update_tarifa_parametrizable($id_tarifa,$params);            
                redirect('tarifa_parametrizable/index');
            }
            else
            {
                $data['_view'] = 'tarifa_parametrizable/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tarifa_parametrizable you are trying to edit does not exist.');
    } 

    /*
     * Deleting tarifa_parametrizable
     */
    function remove($id_tarifa)
    {
        $tarifa_parametrizable = $this->Tarifa_parametrizable_model->get_tarifa_parametrizable($id_tarifa);

        // check if the tarifa_parametrizable exists before trying to delete it
        if(isset($tarifa_parametrizable['id_tarifa']))
        {
            $this->Tarifa_parametrizable_model->delete_tarifa_parametrizable($id_tarifa);
            redirect('tarifa_parametrizable/index');
        }
        else
            show_error('The tarifa_parametrizable you are trying to delete does not exist.');
    }
    
}
