<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_asociado extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipo_asociado_model');
    } 

    /*
     * Listing of tipo_asociado
     */
    function index()
    {
        $data['tipo_asociado'] = $this->Tipo_asociado_model->get_all_tipo_asociado();
        
        $data['_view'] = 'tipo_asociado/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tipo_asociado
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $tipo_asociado_id = $this->Tipo_asociado_model->add_tipo_asociado($params);
            redirect('tipo_asociado/index');
        }
        else
        {            
            $data['_view'] = 'tipo_asociado/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tipo_asociado
     */
    function edit($tipo_asoc)
    {   
        // check if the tipo_asociado exists before trying to edit it
        $data['tipo_asociado'] = $this->Tipo_asociado_model->get_tipo_asociado($tipo_asoc);
        
        if(isset($data['tipo_asociado']['tipo_asoc']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Tipo_asociado_model->update_tipo_asociado($tipo_asoc,$params);            
                redirect('tipo_asociado/index');
            }
            else
            {
                $data['_view'] = 'tipo_asociado/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipo_asociado you are trying to edit does not exist.');
    } 

    /*
     * Deleting tipo_asociado
     */
    function remove($tipo_asoc)
    {
        $tipo_asociado = $this->Tipo_asociado_model->get_tipo_asociado($tipo_asoc);

        // check if the tipo_asociado exists before trying to delete it
        if(isset($tipo_asociado['tipo_asoc']))
        {
            $this->Tipo_asociado_model->delete_tipo_asociado($tipo_asoc);
            redirect('tipo_asociado/index');
        }
        else
            show_error('The tipo_asociado you are trying to delete does not exist.');
    }
    
}
