<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asociado_aux_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get asociado_aux by num
     */
    function get_asociado_aux($num)
    {
        $asociado_aux = $this->db->query("
            SELECT
                *

            FROM
                `asociado_aux`

            WHERE
                `num` = ?
        ",array($num))->row_array();

        return $asociado_aux;
    }
        
    /*
     * Get all asociado_aux
     */
    function get_all_asociado_aux()
    {
        $asociado_aux = $this->db->query("
            SELECT
                *

            FROM
                `asociado_aux`

            WHERE
                1 = 1

            ORDER BY `num` DESC
        ")->result_array();

        return $asociado_aux;
    }
        
    /*
     * function to add new asociado_aux
     */
    function add_asociado_aux($params)
    {
        $this->db->insert('asociado_aux',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update asociado_aux
     */
    function update_asociado_aux($num,$params)
    {
        $this->db->where('num',$num);
        return $this->db->update('asociado_aux',$params);
    }
    
    /*
     * function to delete asociado_aux
     */
    function delete_asociado_aux($num)
    {
        return $this->db->delete('asociado_aux',array('num'=>$num));
    }
}
