<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bolsarol_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bolsarol by 
     */
    function get_bolsarol()
    {
        $bolsarol = $this->db->query("
            SELECT
                *

            FROM
                `bolsarol`

            WHERE
                `` = ?
        ",array())->row_array();

        return $bolsarol;
    }
        
    /*
     * Get all bolsarol
     */
    function get_all_bolsarol()
    {
        $bolsarol = $this->db->query("
            SELECT
                *

            FROM
                `bolsarol`

            WHERE
                1 = 1

            ORDER BY `` DESC
        ")->result_array();

        return $bolsarol;
    }
        
    /*
     * function to add new bolsarol
     */
    function add_bolsarol($params)
    {
        $this->db->insert('bolsarol',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bolsarol
     */
    function update_bolsarol($sql,$params)
    {
        $this->db->where('',$sql);
        return $this->db->update('bolsarol',$params);
    }
    
    /*
     * function to delete bolsarol
     */
    function delete_bolsarol($sql)
    {
        return $this->db->delete('bolsarol',array(''=>$sql));
    }
}
