<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Configuracion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get configuracion by 
     */
    function get_configuracion($)
    {
        $configuracion = $this->db->query("
            SELECT
                *

            FROM
                `configuracion`

            WHERE
                `` = ?
        ",array($))->row_array();

        return $configuracion;
    }
        
    /*
     * Get all configuracion
     */
    function get_all_configuracion()
    {
        $configuracion = $this->db->query("
            SELECT
                *

            FROM
                `configuracion`

            WHERE
                1 = 1

            ORDER BY `` DESC
        ")->result_array();

        return $configuracion;
    }
        
    /*
     * function to add new configuracion
     */
    function add_configuracion($params)
    {
        $this->db->insert('configuracion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update configuracion
     */
    function update_configuracion($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('configuracion',$params);
    }
    
    /*
     * function to delete configuracion
     */
    function delete_configuracion($)
    {
        return $this->db->delete('configuracion',array(''=>$));
    }
}
