<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Descuento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get descuento by id_desc
     */
    function get_descuento($id_desc)
    {
        $descuento = $this->db->query("
            SELECT
                d.*, a.nombres_asoc, a.apellidos_asoc
            FROM
                descuento d
            left join asociado a on d.id_asoc = a.id_asoc
            WHERE
                `id_desc` = ?
        ",array($id_desc))->row_array();

        return $descuento;
    }
    /*
     * function to add new descuento
     */
    function add_descuento($params)
    {
        $this->db->insert('descuento',$params);
        return $this->db->insert_id();
    }
    /* obtiene asociados dada la busqueda en add Descuento */
    function get_buscar_asociado($parametro){
        $cliente = $this->db->query("
            SELECT
                a.id_asoc, a.nombres_asoc, a.apellidos_asoc, foto_asoc
            FROM
                asociado a
            WHERE
                a.estado = 'ACTIVO'
                and (a.nombres_asoc like '%".$parametro."%' or a.apellidos_asoc like '%".$parametro."%' or codigo_asoc = '".$parametro."')
            ORDER BY a.apellidos_asoc, a.nombres_asoc
        ")->result_array();

        return $cliente;
    }
    /* obtiene un asociados de la seleccion de busqueda */
    function get_seleccionar_asociado($parametro){
        $cliente = $this->db->query("
            SELECT
                a.id_asoc, a.nombres_asoc, a.apellidos_asoc
            FROM
                asociado a
            WHERE
                a.id_asoc = $parametro
        ")->result_array();

        return $cliente;
    }    
    /* Get all descuento */
    function get_all_descuento()
    {
        $descuento = $this->db->query("
           SELECT
                a.*
            FROM
                descuento a
            ORDER BY `id_desc` DESC
        ")->result_array();

        return $descuento;
    }
    /*
     * Get all descuento y asociado
     */
    function get_all_descuentoasociado()
    {
        $descuento = $this->db->query("
           SELECT
                d.*, a.apellidos_asoc, a. nombres_asoc 
            FROM
                descuento d
            left join asociado a on d.id_asoc = a.id_asoc
            ORDER BY `id_desc` DESC
        ")->result_array();

        return $descuento;
    }
    
    
    /*
     * function to update descuento
     */
    function update_descuento($id_desc,$params)
    {
        $this->db->where('id_desc',$id_desc);
        return $this->db->update('descuento',$params);
    }
    
    /*
     * function to delete descuento
     */
    function delete_descuento($id_desc)
    {
        return $this->db->delete('descuento',array('id_desc'=>$id_desc));
    }
}
