<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Diametrored_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by diametrored
     */
    function get_diametrored($id_diam)
    {
        $diametrored = $this->db->query("
            SELECT
                *
            FROM
                `diametrored`
            WHERE
                `id_diam` = ?
        ",array($id_diam))->row_array();

        return $diametrored;
    }
        
    /*
     * Get all diametrored
     */
    function get_all_diametrored()
    {
        $diametrored = $this->db->query("
            SELECT
                *
            FROM
                `diametrored`
            WHERE
                1 = 1
        ")->result_array();

        return $diametrored;
    }
        
    /*
     * function to add new diametrored
     */
    function add_diametrored($params)
    {
        $this->db->insert('diametrored',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update diametrored
     */
    function update_diametrored($id_diam,$params)
    {
        $this->db->where('id_diam',$id_diam);
        return $this->db->update('diametrored',$params);
    }
    
    /*
     * function to delete diametrored
     */
    /*function delete_diametrored($id_diam)
    {
        return $this->db->delete('diametrored',array('id_diam'=>$id_diam));
    }*/
}
