<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Direccion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by direccion
     */
    function get_direccion($id_dir)
    {
        $direccion = $this->db->query("
            SELECT
                *
            FROM
                `direccion`
            WHERE
                `id_dir` = ?
        ",array($id_dir))->row_array();

        return $direccion;
    }
        
    /*
     * Get all direccion
     */
    function get_all_direccion()
    {
        $direccion = $this->db->query("
            SELECT
                *
            FROM
                `direccion`
            WHERE
                1 = 1
        ")->result_array();

        return $direccion;
    }
        
    /*
     * function to add new direccion
     */
    function add_direccion($params)
    {
        $this->db->insert('direccion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update direccion
     */
    function update_direccion($id_dir,$params)
    {
        $this->db->where('id_dir',$id_dir);
        return $this->db->update('direccion',$params);
    }
    
}
