<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Documento_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by documento
     */
    function get_documento($id_doc)
    {
        $documento = $this->db->query("
            SELECT
                *
            FROM
                `documento`
            WHERE
                `id_doc` = ?
        ",array($id_doc))->row_array();

        return $documento;
    }
        
    /*
     * Get all documento
     */
    function get_all_documento()
    {
        $documento = $this->db->query("
            SELECT
                *
            FROM
                `documento`
            WHERE
                1 = 1
        ")->result_array();

        return $documento;
    }
        
    /*
     * function to add new documento
     */
    function add_documento($params)
    {
        $this->db->insert('documento',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update documento
     */
    function update_documento($id_doc,$params)
    {
        $this->db->where('id_doc',$id_doc);
        return $this->db->update('documento',$params);
    }
    
}
