<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Factura_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get factura by id_fact
     */
    function get_factura($id_fact)
    {
        $factura = $this->db->query("
            SELECT
                *

            FROM
                `factura`

            WHERE
                `id_fact` = ?
        ",array($id_fact))->row_array();

        return $factura;
    }
        
    /*
     * Get all factura
     */
    function get_all_factura()
    {
        $factura = $this->db->query("
            SELECT
                *

            FROM
                `factura`

            WHERE
                1 = 1

            ORDER BY `id_fact` DESC
        ")->result_array();

        return $factura;
    }
        
    /*
     * function to add new factura
     */
    function add_factura($params)
    {
        $this->db->insert('factura',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update factura
     */
    function update_factura($id_fact,$params)
    {
        $this->db->where('id_fact',$id_fact);
        return $this->db->update('factura',$params);
    }
    
    /*
     * function to delete factura
     */
    function delete_factura($id_fact)
    {
        return $this->db->delete('factura',array('id_fact'=>$id_fact));
    }

    function buscar_asociado($ci)
    {

        $sql = "select * from asociado where nit_asoc = ".$ci." or ci_asoc=".$ci." or codigo_asoc=".$ci;        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }
    function buscar_id_asociado($id)
    {

        $sql = "select * from asociado where id_asoc = ".$id." ";        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }

    function busqueda_asociados($nombre,$apellido)
    {

        $sql = "select * from asociado where nombres_asoc like '%".$nombre."%' and apellidos_asoc like '%".$apellido."%' ";        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }

    function get_pendiente_factura($asociado)
    {

        $sql = "SELECT f.*, l.*
        FROM factura f, lectura l
        WHERE 
        l.id_lec=f.id_lec 
        and f.estado_fact='PENDIENTE'
        and l.id_asoc=".$asociado." ";        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }

    function get_pendiente_detalle($factura)
    {

        $sql = "SELECT *
        FROM detalle_factura 
        WHERE id_fact=".$factura." ";        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }

    function get_recargo_detalle($lectura)
    {

        $sql = "select p.id_param,p.descip_param,p.dias_param,p.monto_param,p.estado,p.detalle_param,  (DATEDIFF(date(now()), t.fecha_lec)) as moradias from parametros p,(select * from lectura where id_lec=".$lectura.") as t where p.estado='ACTIVO' and (DATEDIFF(date(now()), t.fecha_lec)) >= p.dias_param and p.monto_param >0 ";        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }

    function get_datos_factura($factura)
    {

        $sql = "SELECT *
        FROM factura 
        WHERE id_fact=".$factura;        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }

    function recargosadetalle($id_param,$factura_id)
    {

        $sql = "INSERT INTO detalle_factura(
        id_fact,
        cant_detfact,
        descip_detfact,
        punit_detfact,
        desc_detfact,
        total_detfact,
        tipo_detfact) 
        values(
        SELECT
        ".$factura_id.",
        1,
        detalle_param,
        monto_param,
        0,
        monto_param,
        2
        FROM 
        parametros
        WHERE 
        id_param = ".$id_param.")";        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }

    
}
