<?php
/* 
 * Generated by CRUDigniter v3.0 Beta 
 * www.crudigniter.com
 */
 
class Ingreso_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ingreso by id_ing
     */
    function get_ingreso($id_ing)
    {
        return $this->db->get_where('ingreso',array('id_ing'=>$id_ing))->row_array();
    }
    
    /*
     * Get all ingreso
     */
     
      function get_ingresos($id_ing)
    {
         $ingreso = $this->db->query("
            SELECT
                i.*, u.nombre_usu, a.nombres_asoc, a.apellidos_asoc, codigo_asoc

            FROM
                ingreso i

            LEFT JOIN usuario u ON i.id_usu=u.id_usu    
            LEFT JOIN asociado a ON i.id_asoc=a.id_asoc    
            WHERE
                i.id_ing=".$id_ing."

            ORDER BY `id_ing` DESC

            
        ")->result_array();

        return $ingreso;
    }
    function get_all_ingreso()
    {
        
        $ingreso = $this->db->query("
            SELECT
                i.*, u.nombre_usu, a.nombres_asoc, a.apellidos_asoc, a.codigo_asoc

            FROM
                ingreso i

            LEFT JOIN usuario u ON i.id_usu=u.id_usu    
            LEFT JOIN asociado a ON i.id_asoc=a.id_asoc 

            ORDER BY `id_ing` DESC

        ")->result_array();

        return $ingreso;
    }
  
    /*
     * function to add new ingreso
     */
    function add_ingreso($params)
    {
        $this->db->insert('ingreso',$params);
        return $this->db->insert_id();
    }
    
    function fechaingreso($condicion)
    {
       $ingreso = $this->db->query("
        SELECT
                i.*, u.nombre_usu, a.nombres_asoc, a.apellidos_asoc, a.codigo_asoc
            FROM
                ingreso i
            LEFT JOIN usuario u ON i.id_usu=u.id_usu    
            LEFT JOIN asociado a ON i.id_asoc=a.id_asoc 
            WHERE
                1=1
                ".$condicion." 
            ORDER BY i.fechahora_ing DESC 
        "
        )->result_array();
        return $ingreso;
    }
    
    /*
     * function to update ingreso
     */
     
     function numero()
    {
        
        $numrec = $this->db->query("SELECT * FROM parametros")->result_array();
        return $numrec;
    }
     function nombre()
    {
        
        $nom = $this->db->query("SELECT * FROM usuario")->result_array();
        return $nom;
    }
    
    function update_ingreso($id_ing,$params)
    {
        $this->db->where('id_ing',$id_ing);
        $response = $this->db->update('ingreso',$params);
        if($response)
        {
            return "ingreso updated successfully";
        }
        else
        {
            return "Error occuring while updating ingreso";
        }
    }
    
    /*
     * function to delete ingreso
     */
    function delete_ingreso($id_ing)
    {
        $response = $this->db->delete('ingreso',array('id_ing'=>$id_ing));
        if($response)
        {
            return "ingreso deleted successfully";
        }
        else
        {
            return "Error occuring while deleting ingreso";
        }
    }

    function buscar_asociado($buscar)
    {

        $sql = "select * from asociado where nit_asoc = '".$buscar."' or ci_asoc='".$buscar."' or codigo_asoc='".$buscar."' or nombres_asoc like '%".$buscar."%' or apellidos_asoc like '%".$buscar."%' ";        
        $resultado = $this->db->query($sql)->result_array();
        
        return $resultado;
    }


// FUNCIONES DE CONVERSION DE NUMEROS A LETRAS.

 


    
}
