<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ingreso_egresox_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ingreso_egresox by id_ing
     */
    function get_ingreso_egresox($id_ing)
    {
        $ingreso_egresox = $this->db->query("
            SELECT
                *

            FROM
                `ingreso_egresox`

            WHERE
                `id_ing` = ?
        ",array($id_ing))->row_array();

        return $ingreso_egresox;
    }
        
    /*
     * Get all ingreso_egresox
     */
    function get_all_ingreso_egresox()
    {
        $ingreso_egresox = $this->db->query("
            SELECT
                *

            FROM
                `ingreso_egresox`

            WHERE
                1 = 1

            ORDER BY `id_ing` DESC
        ")->result_array();

        return $ingreso_egresox;
    }
        
    /*
     * function to add new ingreso_egresox
     */
    function add_ingreso_egresox($params)
    {
        $this->db->insert('ingreso_egresox',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ingreso_egresox
     */
    function update_ingreso_egresox($id_ing,$params)
    {
        $this->db->where('id_ing',$id_ing);
        return $this->db->update('ingreso_egresox',$params);
    }
    
    /*
     * function to delete ingreso_egresox
     */
    function delete_ingreso_egresox($id_ing)
    {
        return $this->db->delete('ingreso_egresox',array('id_ing'=>$id_ing));
    }
}
