<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lectura_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lectura by id_lec
     */
    function get_lectura($id_lec)
    {
        $lectura = $this->db->query("
            SELECT
                *

            FROM
                `lectura`

            WHERE
                `id_lec` = ?
        ",array($id_lec))->row_array();

        return $lectura;
    }
        
    /*
     * Get all lectura
     */
    function get_all_lectura()
    {
        $lectura = $this->db->query("
            SELECT
                *

            FROM
                `lectura`

            WHERE
                1 = 1

            ORDER BY `id_lec` DESC
        ")->result_array();

        return $lectura;
    }
        
    /*
     * Get all lectura
     */
    function get_all_zonas()
    {
        $sql = "select DISTINCT(zona_asoc) from asociado";
        $zonas = $this->db->query($sql)->result_array();

        return $zonas;
    }
        
    /*
     * Get all lectura
     */
    function get_all_direcciones()
    {
        $sql = "select DISTINCT(direccion_asoc) from asociado";
        $direcciones = $this->db->query($sql)->result_array();

        return $direcciones;
    }
        
    /*
     * function to add new lectura
     */
    function add_lectura($params)
    {
        $this->db->insert('lectura',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lectura
     */
    function update_lectura($id_lec,$params)
    {
        $this->db->where('id_lec',$id_lec);
        return $this->db->update('lectura',$params);
    }
    
    /*
     * function to delete lectura
     */
    function delete_lectura($id_lec)
    {
        return $this->db->delete('lectura',array('id_lec'=>$id_lec));
    }

    /*
     * function para ejecutrar una consulta
     */
    function consultar($sql)
    {
        return $this->db->query($sql)->result_array();
    }

    /*
     * function para realizar uns insercion
     */
    function ejecutar($sql)
    {
        $this->db->query($sql);
        return true;
    }

    function get_lecturasocio($id_lec)
    {
        $sql = "select * from lectura l, factura f, asociado a, detalle_factura d ".
             "where a.id_asoc = l.id_asoc and l.id_lec = f.id_lec and f.id_fact = d.id_fact and ".
             "l.id_lec = ".$id_lec." order by d.id_detfact";

        $asociado = $this->db->query($sql)->result_array();
        return $asociado;
        
    }    

    function get_historico($id_asoc)
    {
        $sql = "select * from lectura
                where id_asoc = {$id_asoc}
                order by id_lec desc
                limit 6";

        $historico = $this->db->query($sql)->result_array();
        return $historico;
        
    }     

    function get_lecturasocio_asoc($id_asoc)
    {
        $sql = "select * from lectura l, factura f, asociado a, detalle_factura d ".
             "where a.id_asoc = l.id_asoc and l.id_lec = f.id_lec and f.id_fact = d.id_fact and ".
             "l.id_lec = (select max(id_lec) from lectura where id_asoc=".$id_asoc.") order by d.id_detfact";

        $asociado = $this->db->query($sql)->result_array();
        return $asociado;
        
    }

    function get_lecturasocio_mes($id_asoc, $mes,$gestion)
    {
        $sql = "select * from lectura l, factura f, asociado a, detalle_factura d ".
             "where a.id_asoc = l.id_asoc and l.id_lec = f.id_lec and f.id_fact = d.id_fact and ".
             "l.id_lec = (select id_lec from lectura where id_asoc = ".$id_asoc." and mes_lec = '".$mes."' and gestion_lec = ".$gestion.") order by d.id_detfact";

        $asociado = $this->db->query($sql)->result_array();
        return $asociado;
        
    }
    /*
     * Get lectura by id_lec
     */
    function get_lectura_basesocio($id_asoc)
    {
        $lectura = $this->db->query("
            SELECT
                *

            FROM
                `lectura`

            WHERE
                `id_asoc` = ?
        ",array($id_asoc))->row_array();

        return $lectura;
    }
    /* obtiene informacion de asociado atravez de id_lec  */
    function get_asociado_fromlecturas($id_lec)
    {
        $lectura = $this->db->query("
            SELECT
                a.`nombres_asoc`, a.`apellidos_asoc`

            FROM
                `lectura` l, `asociado` a

            WHERE
                l.`id_asoc` = a.`id_asoc`
                and l.`id_lec` = $id_lec
        ")->row_array();

        return $lectura;
    }
}
