<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lectura_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lectura by id_lec
     */
    function get_lectura($id_lec)
    {
        $lectura = $this->db->query("
            SELECT
                *

            FROM
                `lectura`

            WHERE
                `id_lec` = ?
        ",array($id_lec))->row_array();

        return $lectura;
    }
        
    /*
     * Get all lectura
     */
    function get_all_lectura()
    {
        $lectura = $this->db->query("
            SELECT
                *

            FROM
                `lectura`

            WHERE
                1 = 1

            ORDER BY `id_lec` DESC
        ")->result_array();

        return $lectura;
    }
        
    /*
     * Get all lectura
     */
    function get_all_zonas()
    {
        $sql = "select DISTINCT(zona_asoc) from asociado";
        $zonas = $this->db->query($sql)->result_array();

        return $zonas;
    }
        
    /*
     * Get all lectura
     */
    function get_all_direcciones()
    {
        $sql = "select DISTINCT(direccion_asoc) from asociado";
        $direcciones = $this->db->query($sql)->result_array();

        return $direcciones;
    }
        
    /*
     * function to add new lectura
     */
    function add_lectura($params)
    {
        $this->db->insert('lectura',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lectura
     */
    function update_lectura($id_lec,$params)
    {
        $this->db->where('id_lec',$id_lec);
        return $this->db->update('lectura',$params);
    }
    
    /*
     * function to delete lectura
     */
    function delete_lectura($id_lec)
    {
        return $this->db->delete('lectura',array('id_lec'=>$id_lec));
    }

    /*
     * function para ejecutrar una consulta
     */
    function consultar($sql)
    {
        return $this->db->query($sql)->result_array();
    }

    
    }
