<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Me_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get me by id_mes
     */
    function get_me($id_mes)
    {
        $me = $this->db->query("
            SELECT
                *

            FROM
                `mes`

            WHERE
                `id_mes` = ?
        ",array($id_mes))->row_array();

        return $me;
    }
        
    /*
     * Get all mes
     */
    function get_all_mes()
    {
        $mes = $this->db->query("
            SELECT
                *

            FROM
                `mes`

            WHERE
                1 = 1

            ORDER BY `id_mes` DESC
        ")->result_array();

        return $mes;
    }
        
    /*
     * function to add new me
     */
    function add_me($params)
    {
        $this->db->insert('mes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update me
     */
    function update_me($id_mes,$params)
    {
        $this->db->where('id_mes',$id_mes);
        return $this->db->update('mes',$params);
    }
    
    /*
     * function to delete me
     */
    function delete_me($id_mes)
    {
        return $this->db->delete('mes',array('id_mes'=>$id_mes));
    }
}
