<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Medidor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get medidor by id_med
     */
    function get_medidor($id_med)
    {
        $medidor = $this->db->query("
            SELECT
                *

            FROM
                `medidor`

            WHERE
                `id_med` = ?
        ",array($id_med))->row_array();

        return $medidor;
    }
        
    /*
     * Get all medidor
     */
    function get_all_medidor()
    {
        $medidor = $this->db->query("
            SELECT
                *

            FROM
                `medidor`

            WHERE
                1 = 1

            ORDER BY `id_med` DESC
        ")->result_array();

        return $medidor;
    }
        
    /*
     * function to add new medidor
     */
    function add_medidor($params)
    {
        $this->db->insert('medidor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update medidor
     */
    function update_medidor($id_med,$params)
    {
        $this->db->where('id_med',$id_med);
        return $this->db->update('medidor',$params);
    }
    
    /*
     * function to delete medidor
     */
    function delete_medidor($id_med)
    {
        return $this->db->delete('medidor',array('id_med'=>$id_med));
    }
}
