<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Modelo_medidor_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by modelo_medidor
     */
    function get_modelo_medidor($id_modelo)
    {
        $modelo_medidor = $this->db->query("
            SELECT
                *
            FROM
                `modelo_medidor`
            WHERE
                `id_modelo` = ?
        ",array($id_modelo))->row_array();

        return $modelo_medidor;
    }
        
    /*
     * Get all modelo_medidor
     */
    function get_all_modelo_medidor()
    {
        $modelo_medidor = $this->db->query("
            SELECT
                *
            FROM
                `modelo_medidor`
            WHERE
                1 = 1
        ")->result_array();

        return $modelo_medidor;
    }
        
    /*
     * function to add new modelo_medidor
     */
    function add_modelo_medidor($params)
    {
        $this->db->insert('modelo_medidor',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update modelo_medidor
     */
    function update_modelo_medidor($id_modelo,$params)
    {
        $this->db->where('id_modelo',$id_modelo);
        return $this->db->update('modelo_medidor',$params);
    }
    
}
