<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Reportes_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get multum by id_multa
     */
    function get_direcciones()
    {

        $sql = "SELECT a.direccion_asoc AS 'direccion', SUM(l.consumo_lec) as 'consumo' FROM asociado a
LEFT JOIN lectura l on a.`id_asoc`=l.`id_asoc`
GROUP BY direccion
ORDER BY direccion";
        $direcciones = $this->db->query($sql)->result_array();

        return $direcciones;
    }
    function reporte_mensual()
    {
        $multa = $this->db->query("
            SELECT
                *

            FROM
                `multa`

            WHERE
                1 = 1

            ORDER BY `id_multa` DESC
        ")->result_array();

        return $multa;
    }
    
}
