<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rol_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rol by id_rol
     */
    function get_rol($id_rol)
    {
        $rol = $this->db->query("
            SELECT
                *

            FROM
                `rol`

            WHERE
                `id_rol` = ?
        ",array($id_rol))->row_array();

        return $rol;
    }
        
    /*
     * Get all rol
     */
    function get_all_rol()
    {
        $rol = $this->db->query("
            SELECT
                *

            FROM
                `rol`

            WHERE
                1 = 1

            ORDER BY `id_rol` DESC
        ")->result_array();

        return $rol;
    }
        
    /*
     * function to add new rol
     */
    function add_rol($params)
    {
        $this->db->insert('rol',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rol
     */
    function update_rol($id_rol,$params)
    {
        $this->db->where('id_rol',$id_rol);
        return $this->db->update('rol',$params);
    }
    
    /*
     * function to delete rol
     */
    function delete_rol($id_rol)
    {
        return $this->db->delete('rol',array('id_rol'=>$id_rol));
    }
}
