<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sistema_red_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by sistema_red
     */
    function get_sistema_red($id_sred)
    {
        $sistema_red = $this->db->query("
            SELECT
                *
            FROM
                `sistema_red`
            WHERE
                `id_sred` = ?
        ",array($id_sred))->row_array();

        return $sistema_red;
    }
        
    /*
     * Get all sistema_red
     */
    function get_all_sistema_red()
    {
        $sistema_red = $this->db->query("
            SELECT
                *
            FROM
                `sistema_red`
            WHERE
                1 = 1
        ")->result_array();

        return $sistema_red;
    }
        
    /*
     * function to add new sistema_red
     */
    function add_sistema_red($params)
    {
        $this->db->insert('sistema_red',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sistema_red
     */
    function update_sistema_red($id_sred,$params)
    {
        $this->db->where('id_sred',$id_sred);
        return $this->db->update('sistema_red',$params);
    }
    
}
