<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_inmueble_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by tipo_inmueble
     */
    function get_tipo_inmueble($id_tin)
    {
        $tipo_inmueble = $this->db->query("
            SELECT
                *
            FROM
                `tipo_inmueble`
            WHERE
                `id_tin` = ?
        ",array($id_tin))->row_array();

        return $tipo_inmueble;
    }
        
    /*
     * Get all tipo_inmueble
     */
    function get_all_tipo_inmueble()
    {
        $tipo_inmueble = $this->db->query("
            SELECT
                *
            FROM
                `tipo_inmueble`
            WHERE
                1 = 1
        ")->result_array();

        return $tipo_inmueble;
    }
        
    /*
     * function to add new tipo_inmueble
     */
    function add_tipo_inmueble($params)
    {
        $this->db->insert('tipo_inmueble',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_inmueble
     */
    function update_tipo_inmueble($id_tin,$params)
    {
        $this->db->where('id_tin',$id_tin);
        return $this->db->update('tipo_inmueble',$params);
    }
    
}
