<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipoinmueble_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get estado by tipoinmueble
     */
    function get_tipoinmueble($id_tin)
    {
        $tipoinmueble = $this->db->query("
            SELECT
                *
            FROM
                `tipo_inmueble`
            WHERE
                `id_tin` = ?
        ",array($id_tin))->row_array();

        return $tipoinmueble;
    }
        
    /*
     * Get all tipoinmueble
     */
    function get_all_tipoinmueble()
    {
        $tipoinmueble = $this->db->query("
            SELECT
                *
            FROM
                `tipo_inmueble`
            WHERE
                1 = 1
        ")->result_array();

        return $tipoinmueble;
    }
        
    /*
     * function to add new tipoinmueble
     */
    function add_tipoinmueble($params)
    {
        $this->db->insert('tipo_inmueble',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipoinmueble
     */
    function update_tipoinmueble($id_tin,$params)
    {
        $this->db->where('id_tin',$id_tin);
        return $this->db->update('tipo_inmueble',$params);
    }
    
}
