<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_usuario by tipo_usuario
     */
    function get_tipo_usuario($tipo_usuario)
    {
        $tipo_usuario = $this->db->query("
            SELECT
                *

            FROM
                `tipo_usuario`

            WHERE
                `tipo_usuario` = ?
        ",array($tipo_usuario))->row_array();

        return $tipo_usuario;
    }
        
    /*
     * Get all tipo_usuario
     */
    function get_all_tipo_usuario()
    {
        $tipo_usuario = $this->db->query("
            SELECT
                *

            FROM
                `tipo_usuario`

            WHERE
                1 = 1

            ORDER BY `tipo_usuario` DESC
        ")->result_array();

        return $tipo_usuario;
    }
        
    /*
     * function to add new tipo_usuario
     */
    function add_tipo_usuario($params)
    {
        $this->db->insert('tipo_usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_usuario
     */
    function update_tipo_usuario($tipo_usuario,$params)
    {
        $this->db->where('tipo_usuario',$tipo_usuario);
        return $this->db->update('tipo_usuario',$params);
    }
    
    /*
     * function to delete tipo_usuario
     */
    function delete_tipo_usuario($tipo_usuario)
    {
        return $this->db->delete('tipo_usuario',array('tipo_usuario'=>$tipo_usuario));
    }
}
