<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tipo_multa_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tipo_multa by tipo
     */
    function get_tipo_multa($tipo)
    {
        $tipo_multa = $this->db->query("
            SELECT
                *

            FROM
                `tipo_multa`

            WHERE
                `tipo` = ?
        ",array($tipo))->row_array();

        return $tipo_multa;
    }
        
    /*
     * Get all tipo_multa
     */
    function get_all_tipo_multa()
    {
        $tipo_multa = $this->db->query("
            SELECT
                *

            FROM
                `tipo_multa`

            WHERE
                1 = 1

            ORDER BY `tipo` DESC
        ")->result_array();

        return $tipo_multa;
    }
        
    /*
     * function to add new tipo_multa
     */
    function add_tipo_multa($params)
    {
        $this->db->insert('tipo_multa',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tipo_multa
     */
    function update_tipo_multa($tipo,$params)
    {
        $this->db->where('tipo',$tipo);
        return $this->db->update('tipo_multa',$params);
    }
    
    /*
     * function to delete tipo_multa
     */
    function delete_tipo_multa($tipo)
    {
        return $this->db->delete('tipo_multa',array('tipo'=>$tipo));
    }
}
