<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Usuario_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get usuario by id_usu
     */
    function get_usuario($id_usu)
    {
        $usuario = $this->db->query("
            SELECT
                *

            FROM
                `usuario`

            WHERE
                `id_usu` = ?
        ",array($id_usu))->row_array();

        return $usuario;
    }
        
    /*
     * Get all usuario
     */
    function get_all_usuario()
    {
        $usuario = $this->db->query("
            SELECT
                *

            FROM
                `usuario`

            WHERE
                1 = 1

            ORDER BY `id_usu` DESC
        ")->result_array();

        return $usuario;
    }
        
    /*
     * function to add new usuario
     */
    function add_usuario($params)
    {
        $this->db->insert('usuario',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update usuario
     */
    function update_usuario($id_usu,$params)
    {
        $this->db->where('id_usu',$id_usu);
        return $this->db->update('usuario',$params);
    }
    
    /*
     * function to delete usuario
     */
    function delete_usuario($id_usu)
    {
        return $this->db->delete('usuario',array('id_usu'=>$id_usu));
    }
}
